# Docker Compose for Upwind MCP Server
version: '3.8'

services:
  upwind-mcp:
    build: .
    container_name: upwind-mcp-server
    environment:
      - UPWIND_CLIENT_ID=${UPWIND_CLIENT_ID}
      - UPWIND_CLIENT_SECRET=${UPWIND_CLIENT_SECRET}
      - UPWIND_BASE_URL=${UPWIND_BASE_URL:-https://api.upwind.io}
      - UPWIND_AUTH_URL=${UPWIND_AUTH_URL:-https://auth.upwind.io}
      - UPWIND_DEFAULT_ORGANIZATION_ID=${UPWIND_DEFAULT_ORGANIZATION_ID}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    stdin_open: true
    tty: true
    # Uncomment if you need port mapping for health checks
    # ports:
    #   - "3000:3000"
